"use client";

import { useState } from "react";
import Link from "next/link";

// ─── Animated background grid ───────────────────────────────────────────────
function GridBackground() {
  return (
    <div className="fixed inset-0 overflow-hidden pointer-events-none z-0">
      {/* Moving grid */}
      <div
        className="absolute inset-0 grid-bg opacity-100"
        style={{ animation: "grid-move 8s linear infinite" }}
      />
      {/* Radial vignette */}
      <div className="absolute inset-0 bg-[radial-gradient(ellipse_80%_80%_at_50%_-20%,rgba(255,255,255,0.04),transparent)]" />
      {/* Floating geometric shapes */}
      <div className="animate-float-slow absolute top-20 left-[10%] w-32 h-32 rounded-full border border-white/5 opacity-40" />
      <div className="animate-float-medium absolute top-40 right-[15%] w-20 h-20 rounded-full border border-white/8 opacity-30" />
      <div
        className="animate-spin-slow absolute top-[60%] left-[5%] w-48 h-48 opacity-[0.03]"
        style={{
          background:
            "conic-gradient(from 0deg, transparent 0deg, rgba(255,255,255,0.5) 60deg, transparent 120deg)",
          borderRadius: "8px",
        }}
      />
      <div className="animate-float-fast absolute bottom-[30%] right-[8%] w-16 h-16 border border-white/5 rotate-45 opacity-30" />
      <div className="animate-float-slow absolute top-[35%] right-[25%] w-3 h-3 bg-white/10 rounded-full" />
      <div className="animate-float-medium absolute top-[70%] left-[30%] w-2 h-2 bg-white/15 rounded-full" />
      <div className="animate-pulse-glow absolute top-[15%] left-[45%] w-1 h-24 bg-gradient-to-b from-transparent via-white/10 to-transparent" />
      <div className="animate-pulse-glow absolute top-[55%] right-[35%] w-1 h-16 bg-gradient-to-b from-transparent via-white/8 to-transparent" />
    </div>
  );
}

// ─── Navbar ──────────────────────────────────────────────────────────────────
function Navbar() {
  return (
    <nav className="relative z-50 flex items-center justify-between px-6 py-5 max-w-6xl mx-auto">
      <div className="flex items-center gap-2">
        <div className="w-6 h-6 rounded-md bg-white flex items-center justify-center">
          <div className="w-3 h-3 rounded-sm bg-black" />
        </div>
        <span className="font-semibold text-white tracking-tight">TradePosts</span>
        <span className="text-white/30 text-sm">.io</span>
      </div>
      <div className="hidden md:flex items-center gap-8 text-sm text-white/50">
        <a href="#benefits" className="hover:text-white/80 transition-colors">Benefits</a>
        <a href="#pricing" className="hover:text-white/80 transition-colors">Pricing</a>
        <a href="#faq" className="hover:text-white/80 transition-colors">FAQ</a>
      </div>
      <Link
        href="/login"
        className="text-sm px-4 py-2 rounded-lg glass hover:bg-white/10 text-white/70 hover:text-white transition-all"
      >
        Sign in
      </Link>
    </nav>
  );
}

// ─── Hero ─────────────────────────────────────────────────────────────────────
function Hero() {
  return (
    <section className="relative z-10 flex flex-col items-center text-center px-6 pt-24 pb-32">
      <div className="inline-flex items-center gap-2 px-3 py-1.5 rounded-full glass text-xs text-white/50 mb-10 animate-fade-in">
        <span className="w-1.5 h-1.5 rounded-full bg-white/40 animate-pulse" />
        AI-powered · Google Business Profile · Set it &amp; forget it
      </div>

      <h1 className="text-gradient text-5xl md:text-7xl font-bold tracking-tight leading-[1.05] max-w-4xl mb-6 animate-slide-up">
        Your Google Business<br />posts, on autopilot.
      </h1>

      <p className="text-white/40 text-lg md:text-xl max-w-xl leading-relaxed mb-12 animate-slide-up" style={{ animationDelay: "0.1s" }}>
        4 professional posts per month, generated by AI and published automatically to your Google Business Profile. Built for plumbers, electricians, HVAC &amp; roofers.
      </p>

      <div className="flex flex-col sm:flex-row gap-3 animate-slide-up" style={{ animationDelay: "0.2s" }}>
        <Link
          href="/login"
          className="px-6 py-3 rounded-xl bg-white text-black font-semibold text-sm hover:bg-white/90 transition-all hover:scale-[1.02] active:scale-[0.98]"
        >
          Start free trial — 14 days
        </Link>
        <a
          href="#benefits"
          className="px-6 py-3 rounded-xl glass text-white/60 hover:text-white text-sm font-medium transition-all hover:bg-white/8"
        >
          See how it works →
        </a>
      </div>

      <p className="mt-6 text-white/20 text-xs animate-fade-in" style={{ animationDelay: "0.4s" }}>
        No credit card required · Cancel anytime · 2-min setup
      </p>

      {/* Mock dashboard preview */}
      <div className="mt-20 w-full max-w-3xl glass-bright rounded-2xl p-1 animate-slide-up" style={{ animationDelay: "0.3s" }}>
        <div className="rounded-xl bg-white/[0.02] p-6 relative overflow-hidden">
          <div className="flex items-center gap-2 mb-4">
            <div className="w-2.5 h-2.5 rounded-full bg-white/10" />
            <div className="w-2.5 h-2.5 rounded-full bg-white/10" />
            <div className="w-2.5 h-2.5 rounded-full bg-white/10" />
            <div className="ml-3 h-5 rounded-md bg-white/5 w-48" />
          </div>
          <div className="grid grid-cols-2 md:grid-cols-4 gap-3">
            {["Jan 7", "Jan 14", "Jan 21", "Jan 28"].map((date, i) => (
              <div key={i} className="glass rounded-lg p-3">
                <div className="text-[10px] text-white/30 mb-2">{date}</div>
                <div className="space-y-1.5">
                  <div className="h-1.5 bg-white/10 rounded-full w-full" />
                  <div className="h-1.5 bg-white/10 rounded-full w-3/4" />
                  <div className="h-1.5 bg-white/10 rounded-full w-5/6" />
                  <div className="h-1.5 bg-white/10 rounded-full w-2/3" />
                </div>
                <div className="mt-3 flex items-center gap-1">
                  <div className="w-1.5 h-1.5 rounded-full bg-white/30 animate-pulse" />
                  <span className="text-[9px] text-white/25">
                    {i < 2 ? "Published" : "Scheduled"}
                  </span>
                </div>
              </div>
            ))}
          </div>
        </div>
      </div>
    </section>
  );
}

// ─── Bento Grid Benefits ──────────────────────────────────────────────────────
function Benefits() {
  const industries = [
    { icon: "🔧", label: "Plumbers", desc: "Emergency repairs & installations" },
    { icon: "⚡", label: "Electricians", desc: "Panels, wiring & EV chargers" },
    { icon: "❄️", label: "HVAC", desc: "AC, heating & air quality" },
    { icon: "🏠", label: "Roofers", desc: "Repairs, gutters & replacements" },
  ];

  return (
    <section id="benefits" className="relative z-10 px-6 py-24 max-w-6xl mx-auto">
      <div className="text-center mb-16">
        <p className="text-white/30 text-sm uppercase tracking-widest mb-4">Why TradePosts</p>
        <h2 className="text-gradient text-4xl md:text-5xl font-bold tracking-tight">
          Built for trades,<br />not tech teams.
        </h2>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
        {/* Large card */}
        <div className="md:col-span-2 glass-bright rounded-2xl p-8 relative overflow-hidden group hover:bg-white/[0.06] transition-all">
          <div className="absolute inset-0 bg-[radial-gradient(circle_at_30%_50%,rgba(255,255,255,0.03),transparent_70%)]" />
          <div className="absolute top-0 right-0 w-48 h-48 rounded-full border border-white/5 translate-x-16 -translate-y-16 group-hover:scale-110 transition-transform duration-700" />
          <div className="relative z-10">
            <div className="w-10 h-10 rounded-xl glass flex items-center justify-center mb-6">
              <span className="text-lg">🤖</span>
            </div>
            <h3 className="text-white text-2xl font-semibold mb-3">AI that speaks your trade</h3>
            <p className="text-white/40 text-base leading-relaxed max-w-md">
              Not generic marketing fluff. Our AI is trained on trade-specific language — it writes like a local expert, not a copywriter who&apos;s never held a wrench.
            </p>
          </div>
        </div>

        {/* Tall card */}
        <div className="glass rounded-2xl p-6 relative overflow-hidden group hover:bg-white/[0.05] transition-all">
          <div className="absolute inset-0 bg-[radial-gradient(circle_at_70%_20%,rgba(255,255,255,0.03),transparent_60%)]" />
          <div className="relative z-10">
            <div className="w-10 h-10 rounded-xl glass flex items-center justify-center mb-6">
              <span className="text-lg">📅</span>
            </div>
            <h3 className="text-white text-xl font-semibold mb-3">Zero effort. Truly.</h3>
            <p className="text-white/40 text-sm leading-relaxed">
              Connect once. Every week, 4 posts go live automatically. No login required. No content calendar. Just more calls.
            </p>
            <div className="mt-6 space-y-2">
              {["Connect Google Business", "AI writes posts", "Cron publishes weekly", "You get more calls"].map((step, i) => (
                <div key={i} className="flex items-center gap-3">
                  <div className="w-5 h-5 rounded-full glass flex items-center justify-center flex-shrink-0">
                    <span className="text-[9px] text-white/40">{i + 1}</span>
                  </div>
                  <span className="text-white/50 text-xs">{step}</span>
                </div>
              ))}
            </div>
          </div>
        </div>

        {/* Industries row */}
        {industries.map((ind, i) => (
          <div key={i} className="glass rounded-2xl p-5 group hover:bg-white/[0.05] transition-all">
            <div className="text-2xl mb-3">{ind.icon}</div>
            <h4 className="text-white font-semibold text-sm mb-1">{ind.label}</h4>
            <p className="text-white/30 text-xs">{ind.desc}</p>
          </div>
        ))}

        {/* Stats card */}
        <div className="md:col-span-2 glass-bright rounded-2xl p-8 relative overflow-hidden group hover:bg-white/[0.06] transition-all">
          <div className="absolute inset-0 bg-[radial-gradient(circle_at_80%_80%,rgba(255,255,255,0.03),transparent_70%)]" />
          <div className="relative z-10">
            <div className="w-10 h-10 rounded-xl glass flex items-center justify-center mb-6">
              <span className="text-lg">📈</span>
            </div>
            <h3 className="text-white text-2xl font-semibold mb-3">More &ldquo;near me&rdquo; calls</h3>
            <p className="text-white/40 text-sm leading-relaxed mb-6 max-w-md">
              Google ranks businesses that post regularly higher in local searches. Businesses posting 4x/month get up to 5× more profile views than those who don&apos;t.
            </p>
            <div className="flex gap-8">
              <div>
                <div className="text-3xl font-bold text-gradient">5×</div>
                <div className="text-white/30 text-xs mt-1">more profile views</div>
              </div>
              <div>
                <div className="text-3xl font-bold text-gradient">4/mo</div>
                <div className="text-white/30 text-xs mt-1">posts auto-published</div>
              </div>
              <div>
                <div className="text-3xl font-bold text-gradient">2min</div>
                <div className="text-white/30 text-xs mt-1">to get started</div>
              </div>
            </div>
          </div>
        </div>

        {/* Additional benefit */}
        <div className="glass rounded-2xl p-6 group hover:bg-white/[0.05] transition-all">
          <div className="w-10 h-10 rounded-xl glass flex items-center justify-center mb-4">
            <span className="text-lg">🔒</span>
          </div>
          <h4 className="text-white font-semibold mb-2">Your brand, your voice</h4>
          <p className="text-white/40 text-sm leading-relaxed">
            Set your tone — professional, friendly, or local. Every post sounds like you wrote it.
          </p>
        </div>
      </div>
    </section>
  );
}

// ─── Pricing ──────────────────────────────────────────────────────────────────
function Pricing() {
  const [annual, setAnnual] = useState(false);

  const plans = [
    {
      name: "Solo",
      price: annual ? 15 : 19,
      period: annual ? "/mo, billed yearly" : "/month",
      desc: "Perfect for a single trade business",
      features: [
        "1 Google Business location",
        "4 AI-written posts per month",
        "Automatic publishing",
        "Tone customization",
        "14-day free trial",
        "Email support",
      ],
      cta: "Start free trial",
      highlight: false,
    },
    {
      name: "Agency",
      price: annual ? 31 : 39,
      period: annual ? "/mo, billed yearly" : "/month",
      desc: "For marketing agencies managing multiple clients",
      features: [
        "Up to 5 locations",
        "4 posts per location per month",
        "Automatic publishing",
        "Custom tones per location",
        "White-label ready",
        "Priority support",
      ],
      cta: "Start free trial",
      highlight: true,
    },
  ];

  return (
    <section id="pricing" className="relative z-10 px-6 py-24 max-w-6xl mx-auto">
      <div className="text-center mb-16">
        <p className="text-white/30 text-sm uppercase tracking-widest mb-4">Pricing</p>
        <h2 className="text-gradient text-4xl md:text-5xl font-bold tracking-tight mb-6">
          Less than one service call.
        </h2>
        <p className="text-white/40 text-base max-w-sm mx-auto">
          At $19/mo, TradePosts pays for itself the first time a new customer calls from your Google profile.
        </p>

        {/* Toggle */}
        <div className="flex items-center justify-center gap-3 mt-8">
          <span className={`text-sm transition-colors ${!annual ? "text-white/70" : "text-white/30"}`}>Monthly</span>
          <button
            onClick={() => setAnnual(!annual)}
            className={`relative w-10 h-6 rounded-full glass transition-all ${annual ? "bg-white/20" : "bg-white/5"}`}
          >
            <span
              className={`absolute top-1 w-4 h-4 rounded-full bg-white transition-all ${annual ? "left-5" : "left-1"}`}
            />
          </button>
          <span className={`text-sm transition-colors ${annual ? "text-white/70" : "text-white/30"}`}>
            Annual <span className="text-white/40 text-xs">–20%</span>
          </span>
        </div>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 gap-4 max-w-3xl mx-auto">
        {plans.map((plan) => (
          <div
            key={plan.name}
            className={`rounded-2xl p-8 relative overflow-hidden transition-all ${
              plan.highlight
                ? "glass-bright border-white/15 hover:bg-white/10"
                : "glass hover:bg-white/[0.05]"
            }`}
          >
            {plan.highlight && (
              <div className="absolute top-4 right-4 px-2 py-0.5 rounded-full bg-white/10 text-[10px] text-white/50 font-medium">
                Popular
              </div>
            )}
            <div className="mb-6">
              <h3 className="text-white font-semibold text-lg mb-1">{plan.name}</h3>
              <p className="text-white/30 text-xs mb-4">{plan.desc}</p>
              <div className="flex items-end gap-1">
                <span className="text-4xl font-bold text-gradient">${plan.price}</span>
                <span className="text-white/30 text-sm mb-1">{plan.period}</span>
              </div>
            </div>
            <ul className="space-y-3 mb-8">
              {plan.features.map((f) => (
                <li key={f} className="flex items-center gap-3 text-white/50 text-sm">
                  <span className="w-4 h-4 rounded-full glass flex items-center justify-center flex-shrink-0 text-white/40 text-[9px]">✓</span>
                  {f}
                </li>
              ))}
            </ul>
            <Link
              href="/login"
              className={`block w-full text-center py-3 rounded-xl text-sm font-semibold transition-all ${
                plan.highlight
                  ? "bg-white text-black hover:bg-white/90 hover:scale-[1.01]"
                  : "glass hover:bg-white/10 text-white/70 hover:text-white"
              }`}
            >
              {plan.cta}
            </Link>
          </div>
        ))}
      </div>

      <p className="text-center text-white/20 text-xs mt-8">
        No credit card required to start · Cancel anytime · Instant setup
      </p>
    </section>
  );
}

// ─── FAQ ─────────────────────────────────────────────────────────────────────
function FAQ() {
  const [open, setOpen] = useState<number | null>(null);

  const faqs = [
    {
      q: "Do I need to know anything about SEO or marketing?",
      a: "Not at all. You connect your Google Business Profile once, tell us your business type, and we handle everything. Most users are set up in under 2 minutes.",
    },
    {
      q: "What kinds of posts does TradePosts write?",
      a: "We write posts about your services, seasonal promotions, tips for homeowners, and local area content. Every post is tailored to your trade and business name — nothing generic.",
    },
    {
      q: "Can I review posts before they go live?",
      a: "Yes. During your trial you can preview all posts in your dashboard before anything goes live. Once you upgrade, posts publish automatically — but you can always pause or edit them.",
    },
    {
      q: "What happens if I have multiple locations?",
      a: "The Agency plan covers up to 5 locations, each with its own posting schedule and AI voice. You manage all of them from a single dashboard.",
    },
    {
      q: "Is this against Google's terms of service?",
      a: "No. We use the official Google Business Profile API, the same one used by tools like Hootsuite and BrightLocal. Automated posts are explicitly supported.",
    },
    {
      q: "What if I want to cancel?",
      a: "Cancel anytime from your account settings — no questions asked. Your posts will stop publishing at the end of your billing period.",
    },
  ];

  return (
    <section id="faq" className="relative z-10 px-6 py-24 max-w-3xl mx-auto">
      <div className="text-center mb-16">
        <p className="text-white/30 text-sm uppercase tracking-widest mb-4">FAQ</p>
        <h2 className="text-gradient text-4xl md:text-5xl font-bold tracking-tight">
          Questions answered.
        </h2>
      </div>

      <div className="space-y-2">
        {faqs.map((faq, i) => (
          <div
            key={i}
            className="glass rounded-xl overflow-hidden hover:bg-white/[0.04] transition-all"
          >
            <button
              onClick={() => setOpen(open === i ? null : i)}
              className="w-full flex items-center justify-between px-6 py-5 text-left"
            >
              <span className="text-white/70 text-sm font-medium pr-8">{faq.q}</span>
              <span
                className={`text-white/30 text-lg flex-shrink-0 transition-transform duration-200 ${
                  open === i ? "rotate-45" : ""
                }`}
              >
                +
              </span>
            </button>
            {open === i && (
              <div className="px-6 pb-5">
                <p className="text-white/40 text-sm leading-relaxed">{faq.a}</p>
              </div>
            )}
          </div>
        ))}
      </div>
    </section>
  );
}

// ─── CTA ─────────────────────────────────────────────────────────────────────
function CTA() {
  return (
    <section className="relative z-10 px-6 py-24 max-w-6xl mx-auto">
      <div className="glass-bright rounded-3xl p-12 md:p-20 text-center relative overflow-hidden">
        <div className="absolute inset-0 bg-[radial-gradient(ellipse_80%_60%_at_50%_100%,rgba(255,255,255,0.04),transparent)]" />
        <div className="absolute top-0 left-1/2 -translate-x-1/2 w-px h-full bg-gradient-to-b from-white/10 via-transparent to-transparent" />

        {/* Floating orbits */}
        <div className="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 w-80 h-80 rounded-full border border-white/[0.04] animate-spin-slow pointer-events-none" />
        <div className="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 w-56 h-56 rounded-full border border-white/[0.04] animate-spin-slow pointer-events-none" style={{ animationDirection: "reverse", animationDuration: "15s" }} />

        <div className="relative z-10">
          <p className="text-white/30 text-sm uppercase tracking-widest mb-6">Get started today</p>
          <h2 className="text-gradient text-4xl md:text-6xl font-bold tracking-tight mb-6">
            Start ranking higher.<br />Stop worrying about posts.
          </h2>
          <p className="text-white/40 text-base max-w-md mx-auto mb-10">
            Join tradespeople who let AI handle their Google presence while they focus on the job.
          </p>
          <Link
            href="/login"
            className="inline-flex items-center gap-2 px-8 py-4 rounded-xl bg-white text-black font-semibold text-sm hover:bg-white/90 transition-all hover:scale-[1.02] active:scale-[0.98]"
          >
            Start your 14-day free trial →
          </Link>
          <p className="mt-4 text-white/20 text-xs">No credit card · 2-minute setup · Cancel anytime</p>
        </div>
      </div>
    </section>
  );
}

// ─── Footer ───────────────────────────────────────────────────────────────────
function Footer() {
  return (
    <footer className="relative z-10 border-t border-white/5 px-6 py-8 max-w-6xl mx-auto">
      <div className="flex flex-col md:flex-row items-center justify-between gap-4">
        <div className="flex items-center gap-2">
          <div className="w-5 h-5 rounded-md bg-white flex items-center justify-center">
            <div className="w-2.5 h-2.5 rounded-sm bg-black" />
          </div>
          <span className="text-white/40 text-sm">TradePosts.io</span>
        </div>
        <div className="flex items-center gap-6 text-white/25 text-xs">
          <a href="#" className="hover:text-white/50 transition-colors">Privacy</a>
          <a href="#" className="hover:text-white/50 transition-colors">Terms</a>
          <a href="mailto:hello@tradeposts.io" className="hover:text-white/50 transition-colors">Contact</a>
        </div>
        <p className="text-white/20 text-xs">© 2026 TradePosts.io</p>
      </div>
    </footer>
  );
}

// ─── Page ─────────────────────────────────────────────────────────────────────
export default function LandingPage() {
  return (
    <main className="relative min-h-screen bg-black overflow-x-hidden">
      <GridBackground />
      <Navbar />
      <Hero />
      <Benefits />
      <Pricing />
      <FAQ />
      <CTA />
      <Footer />
    </main>
  );
}
